---
platform: linux
image_resource:
  type: docker-image
  source: {repository: ansible/ansible-runner, tag: 1.0.1}
inputs:
  - name: mediawiki
run:
  path: sh
  args:
    - -exc
    - |
      mkdir -p ~/.ssh/
      cat > ~/.ssh/access.pem <<EOF
      ((pem-key))
      EOF
      chmod 400 ~/.ssh/access.pem
      ping -c 2 10.0.2.12
      cd mediawiki/ansible/
      export ANSIBLE_HOST_KEY_CHECKING=False
      ansible-playbook -i hosts db-playbook.yml