resources:
  - name: mediawiki
    type: git
    icon: infinity
    source:
      uri: {{github-url}}
      branch: main
jobs:
  - name: db
    plan:
      - in_parallel:
          - get: mediawiki
      - task: deploy
        file: mediawiki/ci/tasks/deploy-db.yml
        vars:
          key: ((pem-key))
  - name: app
    plan:
      - in_parallel:
          - get: mediawiki
            passed: [db]
      - task: deploy
        file: mediawiki/ci/tasks/deploy-app.yml
        vars:
          key: ((pem-key))